name: aios
version: '0.9.1'
summary: AI-powered Operating System Interface
description: |
  Talk to your Linux system in plain English. AIOS is a natural language
  interface powered by Claude that makes Linux accessible to everyone —
  no command line experience required.

  Features:
  - Natural language commands
  - Built-in safety guardrails
  - Plugin system for custom tools
  - Session persistence
  - Background task management
  - Streaming responses
  - Context window management

grade: devel
confinement: classic
base: core24

platforms:
  amd64:
  arm64:

apps:
  aios:
    command: bin/aios
    environment:
      PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
      PYTHONPATH: $SNAP/lib/python3/dist-packages:$SNAP/usr/lib/python3/dist-packages

parts:
  aios:
    plugin: python
    source: .
    python-packages:
      - .
    build-packages:
      - python3-dev
      - libffi-dev
      - libssl-dev
    stage-packages:
      - python3.12-minimal
      - libpython3.12-minimal
      - libpython3.12-stdlib
      - libffi8
    override-prime: |
      craftctl default
      # Create python3 symlink if not present
      if [ ! -f "$CRAFT_PRIME/usr/bin/python3" ]; then
        ln -sf python3.12 "$CRAFT_PRIME/usr/bin/python3"
      fi
